name: securelock
version: git
summary: SecureLock
description: >
  SecureLock is software that lets you make randomly generated passwords.

confinement: devmode

parts:
  securelock:
    plugin: python
    python-version: python2
    source: .

apps:
    securelock:
        command: main.py