
  name: secure-lock
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Secure-Lock: |
    A random password generator.

  grade: stable

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
